sudo: required
language: generic

services:
  - docker

install:
  - docker build -f Dockerfile . -t err-alpine-python3
  - docker build -f Dockerfile2 . -t err-alpine-python2

script:
  - docker images | grep err-alpine-python2
  - docker images | grep err-alpine-python3
