sudo: required
language: generic

services:
  - docker

install:
  - docker build -f Dockerfile . -t err-alpine-python3
  - docker build -f Dockerfile2 . -t err-alpine-python2

script:
  - docker run --rm err-alpine-python3 err -i data
  - docker run --rm err-alpine-python2 err -i data
